src/Entity/Invoice.php
<?php

namespace App\Entity;

use App\Entity\Traits\DateTrait;
use App\Entity\Traits\HasBeenPaidTrait;
use App\Entity\Traits\PaymentDateTrait;
use App\Entity\Traits\TaxBaseTrait;
use App\Entity\Traits\TaxPercentageTrait;
use App\Entity\Traits\TotalTrait;
use App\Enum\PaymentMethodEnum;
use App\Repository\InvoiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Money\Currency;
use Money\Money;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: InvoiceRepository::class)]
#[ORM\UniqueConstraint(name: 'series_number', columns: ['series', 'number'])]
#[UniqueEntity(fields: ['series', 'number'])]
class Invoice extends AbstractBase
{
    use DateTrait;
    use HasBeenPaidTrait;
    use PaymentDateTrait;
    use TaxBaseTrait;
    use TaxPercentageTrait;
    use TotalTrait;

    #[ORM\ManyToOne(targetEntity: Customer::class, inversedBy: 'invoices')]
    private Customer $customer;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private \DateTimeInterface $date;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $sendDate = null;

    #[ORM\Column(type: Types::BOOLEAN, options: ['default' => false])]
    private bool $hasBeenSent = false;

    #[ORM\Column(type: Types::INTEGER, options: ['default' => PaymentMethodEnum::TRANSFER])]
    private int $paymentMethod = PaymentMethodEnum::TRANSFER;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $paymentComments = null;

    #[ORM\Column(type: Types::STRING, length: 64, options: ['default' => self::DEFAULT_NULL_STRING])]
    private string $series = self::DEFAULT_NULL_STRING;

    #[ORM\Column(type: Types::INTEGER, options: ['default' => 0])]
    private int $number = 0;

    #[ORM\Column(type: Types::BOOLEAN, options: ['default' => false])]
    private bool $isIntraCommunityInvoice = false;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $customerReference = null;

    #[ORM\Column(type: Types::FLOAT, precision: 2, options: ['default' => 0.00])]
    private float $discountPercentage = 0.00;

    #[Assert\Valid]
    #[ORM\OneToMany(mappedBy: 'invoice', targetEntity: InvoiceLine::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private ?Collection $invoiceLines;

    public function __construct()
    {
        $this->invoiceLines = new ArrayCollection();
    }

    public function getCustomer(): Customer
    {
        return $this->customer;
    }

    public function setCustomer(Customer $customer): self
    {
        $this->customer = $customer;

        return $this;
    }

    public function getSendDate(): ?\DateTimeInterface
    {
        return $this->sendDate;
    }

    public function setSendDate(?\DateTimeInterface $sendDate): self
    {
        $this->sendDate = $sendDate;

        return $this;
    }

    public function hasBeenSent(): bool
    {
        return $this->hasBeenSent;
    }

    public function getHasBeenSent(): bool
    {
        return $this->hasBeenSent();
    }

    public function setHasBeenSent(bool $hasBeenSent): self
    {
        $this->hasBeenSent = $hasBeenSent;

        return $this;
    }

    public function getPaymentMethod(): int
    {
        return $this->paymentMethod;
    }

    public function setPaymentMethod(int $paymentMethod): self
    {
        $this->paymentMethod = $paymentMethod;

        return $this;
    }

    public function getPaymentComments(): ?string
    {
        return $this->paymentComments;
    }

    public function setPaymentComments(?string $paymentComments): self
    {
        $this->paymentComments = $paymentComments;

        return $this;
    }

    public function getSeries(): string
    {
        return $this->series;
    }

    public function setSeries(string $series): self
    {
        $this->series = $series;

        return $this;
    }

    public function getNumber(): int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getSerialNumber(): string
    {
        return $this->getSeries().self::DEFAULT_SERIAL_NUMBER_SEPARATOR.$this->getNumber();
    }

    public function getSluggedSerialNumber(): string
    {
        return $this->getSeries().'-'.sprintf('%03d', $this->getNumber());
    }

    public function getSluggedSerialNumberWithName(): string
    {
        return $this->getSluggedSerialNumber().' · '.$this->getCustomer()->getCommercialOrFiscalName();
    }

    public function isIntraCommunityInvoice(): bool
    {
        return $this->isIntraCommunityInvoice;
    }

    public function getIsIntraCommunityInvoice(): bool
    {
        return $this->isIntraCommunityInvoice();
    }

    public function setIsIntraCommunityInvoice(bool $isIntraCommunityInvoice): self
    {
        $this->isIntraCommunityInvoice = $isIntraCommunityInvoice;

        return $this;
    }

    public function getCustomerReference(): ?string
    {
        return $this->customerReference;
    }

    public function setCustomerReference(?string $customerReference): Invoice
    {
        $this->customerReference = $customerReference;

        return $this;
    }

    public function getDiscountPercentage(): float
    {
        return $this->discountPercentage;
    }

    public function setDiscountPercentage(float $discountPercentage): self
    {
        $this->discountPercentage = $discountPercentage;

        return $this;
    }

    public function getInvoiceLines(): Collection
    {
        return $this->invoiceLines;
    }

    public function addInvoiceLine(InvoiceLine $invoiceLine): self
    {
        if (!$this->invoiceLines->contains($invoiceLine)) {
            $invoiceLine->setInvoice($this);
            $this->invoiceLines->add($invoiceLine);
        }

        return $this;
    }

    public function removeInvoiceLine(InvoiceLine $invoiceLine): self
    {
        if ($this->invoiceLines->contains($invoiceLine)) {
            $this->invoiceLines->removeElement($invoiceLine);
        }

        return $this;
    }

    public function calculateBaseAmount(): Money
    {
        $result = new Money(0, new Currency(self::DEFAULT_CURRENCY_STRING));
        /** @var InvoiceLine $line */
        foreach ($this->getInvoiceLines() as $line) {
            $result = $result->add($line->calculateBaseAmount());
        }

        return $result;
    }

    public function calculateDiscountBaseAmount(): Money
    {
        $result = $this->calculateBaseAmount();

        return $result->multiply($this->getDiscountPercentage())->divide(100);
    }

    public function calculateTaxBaseAmount(): Money
    {
        $result = $this->calculateBaseAmount();
        $result = $result->subtract($this->calculateDiscountBaseAmount());

        return $result->multiply($this->getTaxPercentage())->divide(100);
    }

    public function calculateTotalBaseAmount(): Money
    {
        $result = new Money(0, new Currency(self::DEFAULT_CURRENCY_STRING));
        /** @var InvoiceLine $line */
        foreach ($this->getInvoiceLines() as $line) {
            $result = $result->add($line->calculateBaseAmount());
        }
        $discountAmount = $result->multiply($this->getDiscountPercentage())->divide(100);
        $resultMinusDiscount = $result->subtract($discountAmount);
        $this->setTaxBase($resultMinusDiscount);
        $resultTax = $resultMinusDiscount->multiply($this->getTaxPercentage())->divide(100);
        $this->setTotal($resultMinusDiscount->add($resultTax));

        return $result;
    }

    public function __toString(): string
    {
        return $this->id ? $this->getSluggedSerialNumberWithName() : self::DEFAULT_NULL_STRING.self::DEFAULT_SERIAL_NUMBER_SEPARATOR.self::DEFAULT_NULL_STRING;
    }
}

src/Entity/Traits/DateTrait.php
<?php

namespace App\Entity\Traits;

use App\Entity\AbstractBase;

trait DateTrait
{
    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function getDateString(): string
    {
        return AbstractBase::convertDateAsString($this->getDate());
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
}

templates/components/all_years_medians_table.html.twig
{% if computed.getYearlyMedians | length > 0 %}
    <div class="table-responsive">
        <table class="table table-bordered margin-bottom-none">
            <thead>
            <tr>
                <th class="text-right">{{ 'Year' | trans }}</th>
                <th class="text-right">{{ 'Incoming' | trans }}</th>
                <th class="text-right">{{ 'Expense' | trans }}</th>
                <th class="text-right">{{ 'Result' | trans }}</th>
                <th class="text-right">{{ 'Performance' | trans }}</th>
            </tr>
            </thead>
            <tbody>
            {% for yearly_medians in computed.getYearlyMedians %}
                <tr>
                    <td class="text-right">{{ yearly_medians.year }}</td>
                    <td class="text-right text-success">{{ yearly_medians.monthlyMedianInvoiced | m }}</td>
                    <td class="text-right text-danger">-{{ yearly_medians.monthlyMedianExpensed | m }}</td>
                    <td class="text-right {% if yearly_medians.monthlyMedianResult | money_as_float >= 0 %}text-success{% else %}text-danger{% endif %}">{{ yearly_medians.monthlyMedianResult | m }}</td>
                    <td class="text-right {% if yearly_medians.performance >= 0 %}text-success{% else %}text-danger{% endif %}">{{ yearly_medians.performance | percentage }}</td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr class="active">
                <th class="text-right">{{ 'Total' | trans }}</th>
                <th class="text-right text-success">{{ computed.totalInvoiced | m }}</th>
                <th class="text-right text-danger">-{{ computed.totalExpensed | m }}</th>
                <th class="text-right {% if computed.totalResult | money_as_float >= 0 %}text-success{% else %}text-danger{% endif %}">{{ computed.totalResult | m }}</th>
                <th class="text-right {% if computed.totalPerformance >= 0 %}text-success{% else %}text-danger{% endif %}">{{ computed.totalPerformance | percentage }}</th>
            </tr>
            </tfoot>
        </table>
    </div>
{% else %}
    <div class="alert alert-warning margin-bottom-none" role="alert">
        <i class="fa fa-exclamation-triangle fa-fw"></i> {{ 'No Results Found' | trans }}
    </div>
{% endif %}

templates/components/all_years_performance_table.html.twig
{% if computed.monthlyPerformances | length > 0 %}
    <div class="table-responsive">
        <table class="table table-bordered margin-bottom-none">
            <thead>
            <tr>
                <th class="text-right">{{ 'Year' | trans }}</th>
                <th class="text-right">{{ 'New Customers' | trans }}</th>
                <th class="text-right">{{ 'Incoming' | trans }}</th>
                <th class="text-right">{{ 'Expense' | trans }}</th>
                <th class="text-right">{{ 'Result' | trans }}</th>
            </tr>
            </thead>
            <tbody>
            {% for monthly_performance in computed.monthlyPerformances %}
                <tr>
                    <td class="text-right">{{ monthly_performance.year }}</td>
                    <td class="text-right">{{ monthly_performance.newCustomersAmount }}</td>
                    <td class="text-right text-success">{{ monthly_performance.invoiced | m }}</td>
                    <td class="text-right text-danger">-{{ monthly_performance.expensed | m }}</td>
                    <td class="text-right {% if monthly_performance.result | money_as_float >= 0 %}text-success{% else %}text-danger{% endif %}">{{ monthly_performance.result | m }}</td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr class="active">
                <th class="text-right">{{ 'Total' | trans }}</th>
                <th class="text-right">{{ computed.totalNewCustomers | i }}</th>
                <th class="text-right text-success">{{ computed.totalInvoiced | m }}</th>
                <th class="text-right text-danger">-{{ computed.totalExpensed | m }}</th>
                <th class="text-right {% if computed.totalResult | money_as_float >= 0 %}text-success{% else %}text-danger{% endif %}">{{ computed.totalResult | m }}</th>
            </tr>
            </tfoot>
        </table>
    </div>
{% else %}
    <div class="alert alert-warning margin-bottom-none" role="alert">
        <i class="fa fa-exclamation-triangle fa-fw"></i> {{ 'No Results Found' | trans }}
    </div>
{% endif %}

templates/components/dashboard_performance_chart.html.twig
<div class="col-xs-12">
    <div class="row">
        {% if app.user and app.user.googleCredentialsAccepted %}
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="info-box bg-light-blue">
                    <span class="info-box-icon"><i class="far fa-eye"></i></span>
                    <div class="info-box-content">
                        <span class="info-box-text">{{ 'Web visits' | trans }}</span>
                        <span class="info-box-number">{{ computed.get30DaysAgoTotalVisitsAmount | i }} {{ 'last 30 days' | trans }}</span>
                        <div class="progress"></div>
                        <span class="progress-description">{{ computed.get365DaysAgoTotalVisitsAmount | i }} {{ 'last 365 days' | trans }}</span>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <a href="{% if computed.totalProjectsAmount == 0 %}{{ path('admin_app_project_create') }}{% else %}{{ path('admin_app_project_list') }}{% endif %}">
                <div class="info-box bg-light-blue">
                    <span class="info-box-icon"><i class="far fa-folder-open"></i></span>
                    <div class="info-box-content">
                        <span class="info-box-text">{{ 'projects' | trans }}</span>
                        <span class="info-box-number">{{ computed.totalProjectsAmount | i }}</span>
                        {% if computed.totalProjectsAmount == 0 %}
                            <div class="progress"></div>
                            <span class="progress-description"><i class="fa fa-plus-circle fa-fw"></i> {{ 'Add new' | trans }}</span>
                        {% endif %}
                    </div>
                </div>
            </a>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <a href="{{ path('admin_app_contactmessage_list') }}">
                <div class="info-box bg-aqua">
                    <span class="info-box-icon"><i class="far fa-envelope-open"></i></span>
                    <div class="info-box-content">
                        <span class="info-box-text">{{ 'Contact Message List' | trans }} {{ 'received' | trans }}</span>
                        <span class="info-box-number">{{ computed.totalContactMessagesAmount | i }}</span>
                        {% if computed.responsePendingContactMessagesAmount > 0 %}
                            <div class="progress"></div>
                            <span class="progress-description">{{ computed.responsePendingContactMessagesAmount | i }} {{ 'response pending' | trans }}</span>
                        {% endif %}
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <a href="{% if computed.totalProvidersAmount == 0 %}{{ path('admin_app_provider_create') }}{% else %}{{ path('admin_app_provider_list') }}{% endif %}">
                <div class="info-box bg-teal">
                    <span class="info-box-icon"><i class="far fa-user"></i></span>
                    <div class="info-box-content">
                        <span class="info-box-text">{{ 'Provider List' | trans }}</span>
                        <span class="info-box-number">{{ computed.totalProvidersAmount | i }}</span>
                        {% if computed.totalProvidersAmount == 0 %}
                            <div class="progress"></div>
                            <span class="progress-description"><i class="fa fa-plus-circle fa-fw"></i> {{ 'Add new' | trans }}</span>
                        {% endif %}
                    </div>
                </div>
            </a>
        </div>
        {% if computed.totalProvidersAmount > 0 %}
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <a href="{% if computed.totalExpensesAmount == 0 %}{{ path('admin_app_expense_create') }}{% else %}{{ path('admin_app_expense_list') }}{% endif %}">
                    <div class="info-box bg-yellow">
                        <span class="info-box-icon"><i class="fa fa-file-text-o"></i></span>
                        <div class="info-box-content">
                            <span class="info-box-text">{{ 'Expense List' | trans }} {{ 'receipts' | trans }}</span>
                            <span class="info-box-number">{{ computed.totalExpensesAmount | i }}</span>
                            {% if computed.totalExpensesAmount == 0 %}
                                <div class="progress"></div>
                                <span class="progress-description"><i class="fa fa-plus-circle fa-fw"></i> {{ 'Add new' | trans }}</span>
                            {% endif %}
                        </div>
                    </div>
                </a>
            </div>
        {% endif %}
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <a href="{% if computed.totalCustomersAmount == 0 %}{{ path('admin_app_customer_create') }}{% else %}{{ path('admin_app_customer_list') }}{% endif %}">
                <div class="info-box bg-teal">
                    <span class="info-box-icon"><i class="far fa-user"></i></span>
                    <div class="info-box-content">
                        <span class="info-box-text">{{ 'Customer List' | trans }}</span>
                        <span class="info-box-number">{{ computed.totalCustomersAmount | i }}</span>
                        {% if computed.totalCustomersAmount == 0 %}
                            <div class="progress"></div>
                            <span class="progress-description"><i class="fa fa-plus-circle fa-fw"></i> {{ 'Add new' | trans }}</span>
                        {% endif %}
                    </div>
                </div>
            </a>
        </div>
        {% if computed.totalCustomersAmount > 0 %}
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <a href="{% if computed.totalInvoicesAmount == 0 %}{{ path('admin_app_invoice_create') }}{% else %}{{ path('admin_app_invoice_list') }}{% endif %}">
                    <div class="info-box bg-yellow">
                        <span class="info-box-icon"><i class="fa fa-file-text-o"></i></span>
                        <div class="info-box-content">
                            <span class="info-box-text">{{ 'Invoice List' | trans }} {{ 'emitted' | trans }}</span>
                            <span class="info-box-number">{{ computed.totalInvoicesAmount | i }}</span>
                            {% if computed.totalInvoicesAmount == 0 %}
                                <div class="progress"></div>
                                <span class="progress-description"><i class="fa fa-plus-circle fa-fw"></i> {{ 'Add new' | trans }}</span>
                            {% endif %}
                        </div>
                    </div>
                </a>
            </div>
        {% endif %}
    </div>
</div>

templates/components/last_12_months_top_ten_customer_earnings_table.html.twig
{% if computed.topTenCustomerEarnings | length > 0 %}
    <div class="table-responsive">
        <table class="table table-bordered margin-bottom-none">
            <thead>
            <tr>
                <th class="text-right">{{ 'Number Short' | trans }}</th>
                <th>{{ 'Customer' | trans }}</th>
                <th>{{ 'City' | trans }}</th>
                <th class="text-right">{{ 'Incoming' | trans }}</th>
            </tr>
            </thead>
            <tbody>
            {% for customer_earnings in computed.topTenCustomerEarnings %}
                <tr>
                    <td class="text-right">{{ customer_earnings.number }}</td>
                    <td>{{ customer_earnings.customer }}</td>
                    <td>{{ customer_earnings.city }}</td>
                    <td class="text-right text-success">{{ customer_earnings.earnings | m }}</td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr class="active">
                <th colspan="3" class="text-right">{{ 'Total' | trans }}</th>
                <th class="text-right text-success">{{ computed.total | m }}</th>
            </tr>
            </tfoot>
        </table>
    </div>
{% else %}
    <div class="table-responsive">
        <table class="table margin-bottom-none">
            <tbody>
            <tr class="warning">
                <td><i class="fa fa-exclamation-triangle fa-fw"></i> {{ 'No Results Found' | trans }}. {{ 'Create A New Customer Warning Help' | trans }}</td>
            </tr>
            </tbody>
        </table>
    </div>
{#    <div class="alert alert-warning margin-bottom-none" role="alert">#}
{#        <i class="fa fa-exclamation-triangle fa-fw"></i> {{ 'No Results Found' | trans }}#}
{#    </div>#}
{% endif %}

templates/components/last_months_invoicing_resume_chart.html.twig
{{ render_chart(computed.chart) }}

templates/components/top_ten_customer_earnings_table.html.twig
{% extends 'components/last_12_months_top_ten_customer_earnings_table.html.twig' %}

templates/components/total_retaining_earnings_chart.html.twig
{{ render_chart(computed.chart) }}

templates/components/unpaid_invoices_table.html.twig
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title text-info"><i class="fas fa-briefcase fa-fw"></i> {{ 'Unpaid Invoices' | trans }}</h3>
        <div class="box-tools pull-right">
            <a class="btn btn-outline-primary" href="{{ path('admin_app_invoice_list') }}" title="{{ 'Show All' | trans }}"><i class="far fa-list-alt"></i></a>
        </div>
    </div>
    <div class="box-body no-padding">
        {% if computed.unpaidInvoices | length > 0 %}
            <div class="table-responsive">
                <table class="table margin-bottom-none">
                    <tbody>
                    {% set totalTax = 0 %}
                    {% for invoice in computed.unpaidInvoices %}
                        {% set totalTax = totalTax + invoice.taxBaseAmount %}
                        <tr>
                            <td class="text-center" style="width:75px">{{ invoice.sluggedSerialNumber }}</td>
                            <td class="text-center" style="width:90px">{{ invoice.dateString }}</td>
                            <td><a href="{{ path('admin_app_customer_edit', {'id': invoice.customer.id}) }}">{{ invoice.customer }}</a></td>
                            <td class="text-right">{{ invoice.taxBase | money_localized_format }}</td>
                            <td class="text-right" style="width:60px">
                                <div class="btn-group">
                                    <a href="{{ path('admin_app_invoice_edit', {'id': invoice.id}) }}" class="btn btn-xs btn-default" title="{{ 'Edit' | trans }}">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>
                                    <a data-controller="pdf-button"
                                       data-action="pdf-button#clicked"
                                       data-toggle="modal"
                                       data-target="#pdf-preview-modal"
                                       data-pdf-button-attachment-value="{{ invoice.id }}"
                                       data-pdf-button-path-value="{{ path('admin_app_invoice_pdf', {'id': invoice.id}) }}" class="btn btn-xs btn-default" title="{{ 'PDF' | trans }}">
                                        <i class="far fa-file-pdf"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    {% set totalTax = totalTax * 0.01 %}
                    </tbody>
                    <tfoot>
                    <tr class="active">
                        <th colspan="3" class="text-right">{{ 'Total' | trans | upper }} {{ 'Total Base' | trans | upper }}</th>
                        <th class="text-right">{{ totalTax | eur }}</th>
                        <th></th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        {% else %}
            <div class="table-responsive">
                <table class="table margin-bottom-none">
                    <tbody>
                    <tr class="success">
                        <td><i class="fa fa-thumbs-o-up fa-fw"></i> {{ 'No Unpaid Invoices Found' | trans }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        {% endif %}
    </div>
</div>